# Generated by Django 2.0.8 on 2019-01-19 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', help_text='Enter the brand name of the item', max_length=50)),
                ('model', models.CharField(default='Generic', help_text='Enter the model of the item', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True)),
                ('date_of_acquire', models.DateField(default=datetime.date.today, help_text='Enter the date of acquire')),
                ('status', models.CharField(choices=[('WK', 'Working'), ('OO', 'Out of Order'), ('IM', 'In Maintenance')], default='WK', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', help_text='Enter the brand name of the item', max_length=50)),
                ('model', models.CharField(default='Generic', help_text='Enter the model of the item', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True)),
                ('date_of_acquire', models.DateField(default=datetime.date.today, help_text='Enter the date of acquire')),
                ('status', models.CharField(choices=[('WK', 'Working'), ('OO', 'Out of Order'), ('IM', 'In Maintenance')], default='WK', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', help_text='Enter the brand name of the item', max_length=50)),
                ('model', models.CharField(default='Generic', help_text='Enter the model of the item', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True)),
                ('date_of_acquire', models.DateField(default=datetime.date.today, help_text='Enter the date of acquire')),
                ('status', models.CharField(choices=[('WK', 'Working'), ('OO', 'Out of Order'), ('IM', 'In Maintenance')], default='WK', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', help_text='Enter the brand name of the item', max_length=50)),
                ('model', models.CharField(default='Generic', help_text='Enter the model of the item', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True)),
                ('date_of_acquire', models.DateField(default=datetime.date.today, help_text='Enter the date of acquire')),
                ('status', models.CharField(choices=[('WK', 'Working'), ('OO', 'Out of Order'), ('IM', 'In Maintenance')], default='WK', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('no_of_ports', models.PositiveSmallIntegerField(help_text='Enter the number of ports')),
                ('no_of_SFP_ports', models.PositiveSmallIntegerField(help_text='Enter the number of SFP ports')),
            ],
            options={
                'verbose_name_plural': 'Network Switches',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', help_text='Enter the brand name of the item', max_length=50)),
                ('model', models.CharField(default='Generic', help_text='Enter the model of the item', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True)),
                ('date_of_acquire', models.DateField(default=datetime.date.today, help_text='Enter the date of acquire')),
                ('status', models.CharField(choices=[('WK', 'Working'), ('OO', 'Out of Order'), ('IM', 'In Maintenance')], default='WK', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Enter the ip address for this printer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(help_text='Enter the room number', max_length=20, primary_key=True, serialize=False)),
                ('floor', models.PositiveSmallIntegerField(help_text='In which floor is this room?')),
            ],
        ),
        migrations.AddField(
            model_name='printer',
            name='room',
            field=models.ForeignKey(help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='room',
            field=models.ForeignKey(help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='room',
            field=models.ForeignKey(help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AddField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AddField(
            model_name='additionalitem',
            name='room',
            field=models.ForeignKey(help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
    ]
