# Generated by Django 2.0.8 on 2019-03-13 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Generic', help_text='Enter the category of the item', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor', models.PositiveSmallIntegerField(help_text='Enter the floor', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', help_text='Enter the brand name of the item', max_length=50)),
                ('model', models.CharField(default='Generic', help_text='Enter the model of the item', max_length=50)),
                ('cost_per_item', models.DecimalField(decimal_places=2, help_text='Enter the cost per item', max_digits=10, null=True)),
                ('date_of_acquire', models.DateField(default=datetime.date.today, help_text='Enter the date of acquire')),
                ('working', models.IntegerField(default=0)),
                ('in_maintenance', models.IntegerField(default=0)),
                ('out_of_order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(help_text='Select the category of the equipment', on_delete=django.db.models.deletion.CASCADE, to='inventory.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.PositiveSmallIntegerField(help_text='Enter the room number', primary_key=True, serialize=False)),
                ('room_name', models.CharField(default='Generic', help_text='Enter the name of the room', max_length=20)),
                ('floor', models.ForeignKey(help_text='In which floor is this room?', on_delete=django.db.models.deletion.CASCADE, to='inventory.Floor')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
    ]
