# Generated by Django 2.0.7 on 2019-01-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor', models.PositiveSmallIntegerField(help_text='Enter the floor', primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(help_text='In which floor is this room?', on_delete=django.db.models.deletion.CASCADE, to='inventory.Floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.PositiveSmallIntegerField(help_text='Enter the room number', primary_key=True, serialize=False),
        ),
    ]
