# Generated by Django 2.0.8 on 2019-03-14 09:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190314_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extra_value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
