# Generated by Django 2.0.7 on 2019-01-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190120_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempRoom',
            fields=[
                ('room_no', models.PositiveSmallIntegerField(help_text='Enter the room number', primary_key=True, serialize=False)),
                ('floor', models.ForeignKey(help_text='In which floor is this room?', on_delete=django.db.models.deletion.CASCADE, to='inventory.Floor')),
            ],
        ),
    ]
