# Generated by Django 2.0.7 on 2019-01-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_temproom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temproom',
            name='floor',
            field=models.ForeignKey(blank=True, help_text='In which floor is this room?', on_delete=django.db.models.deletion.CASCADE, to='inventory.Floor'),
        ),
        migrations.AlterField(
            model_name='temproom',
            name='room_no',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the room number', primary_key=True, serialize=False),
        ),
    ]
