# Generated by Django 2.0.7 on 2019-01-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190120_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temproom',
            name='room_no',
            field=models.PositiveSmallIntegerField(default=0, help_text='Enter the room number', primary_key=True, serialize=False),
        ),
    ]
