# Generated by Django 2.0.7 on 2019-01-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190120_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temproom',
            name='floor',
        ),
        migrations.DeleteModel(
            name='tempRoom',
        ),
    ]
