# Generated by Django 2.0.7 on 2019-03-02 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190120_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitem',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today, help_text='Enter the date of acquire'),
        ),
        migrations.AlterField(
            model_name='additionalitem',
            name='room',
            field=models.ForeignKey(blank='True', help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today, help_text='Enter the date of acquire'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(blank='True', help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today, help_text='Enter the date of acquire'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='room',
            field=models.ForeignKey(blank='True', help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today, help_text='Enter the date of acquire'),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='room',
            field=models.ForeignKey(blank='True', help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today, help_text='Enter the date of acquire'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='room',
            field=models.ForeignKey(blank='True', help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
    ]
