# Generated by Django 2.0.7 on 2019-03-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190302_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitem',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, help_text='Enter the cost of the item', max_digits=10, null=True),
        ),
    ]
