# Generated by Django 2.0.7 on 2019-03-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190302_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkswitch',
            name='no_of_SFP_ports',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the number of SFP ports'),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='no_of_ports',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the number of ports'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Enter the ip address for this printer', null=True),
        ),
    ]
