# Generated by Django 2.0.7 on 2019-03-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190302_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkswitch',
            name='no_of_SFP_ports',
            field=models.PositiveSmallIntegerField(blank='True', help_text='Enter the number of SFP ports', null='True'),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='no_of_ports',
            field=models.PositiveSmallIntegerField(blank='True', help_text='Enter the number of ports', null='True'),
        ),
    ]
