# Generated by Django 2.0.7 on 2019-03-03 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20190302_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitem',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionalitem',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='additionalitem',
            name='model',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalitem',
            name='name',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalitem',
            name='room',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='room',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='model',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='name',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='room',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='cost',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='date_of_acquire',
            field=models.DateField(blank='True', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(default='Generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='room',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
    ]
